/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/raspberry/scene.gltf 
Author: objets3D (https://sketchfab.com/objets3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/raspberry-d045eaf534384d9eb926245a5a09ead4
Title: Raspberry
*/

import { useGLTF } from "@react-three/drei";

export function Raspberry(props) {
  const { nodes, materials } = useGLTF("../../public/raspberry/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-18.193, 12.471, -1.917]}
        rotation={[-1.278, -0.539, 0.426]}
      >
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.rpi_L}
          position={[-66.955, -48.678, -43.703]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("../../public/raspberry/scene.gltf");
